images:
  - gcr.io/$PROJECT_ID/compound-subgraph-wrapper:$TAG_NAME
options:
  machineType: "N1_HIGHCPU_32"
timeout: 900s
steps:
  # Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/compound-subgraph-wrapper:$TAG_NAME",
        ".",
      ]

  # Inject Docker image into the deployment manifest
  - name: "gcr.io/$PROJECT_ID/kustomize"
    args:
      [
        "edit",
        "set",
        "image",
        "compound-subgraph-wrapper=gcr.io/$PROJECT_ID/compound-subgraph-wrapper:$TAG_NAME",
      ]
    dir: k8s/base
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=hosted-service"

  # Deploy configuration
  - name: "gcr.io/$PROJECT_ID/kustomize"
    args: ["build", "k8s/overlays/production/"]
    env:
      - "APPLY=true"
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=hosted-service"
