apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: compound-subgraph-wrapper
spec:
  template:
    spec:
      containers:
        - name: wrapper
          env:
            - name: SUBGRAPH_QUERY_ENDPOINT
              value: http://query-node.default.svc.cluster.local/subgraphs/name/graphprotocol/compound-v2
            - name: SUBGRAPH_SUBSCRIPTION_ENDPOINT
              value: ws://query-node.default.svc.cluster.local/subgraphs/name/graphprotocol/compound-v2
