apiVersion: v1
kind: Service
metadata:
  name: compound-subgraph-wrapper
spec:
  type: NodePort
  selector:
    app: compound-subgraph-wrapper
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
